# Generated by Django 5.1.5 on 2025-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_liked_by_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'email is required', 'max_length': 'email must be 50 characters or less', 'unique': 'email already exists'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'email is required', 'max_length': 'email must be 50 characters or less', 'unique': 'email already exists'}, max_length=50, unique=True),
        ),
    ]
