# Generated by Django 5.1.5 on 2025-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'username is required', 'max_length': 'email must be 50 characters or less', 'unique': 'username already exists'}, max_length=50, unique=True),
        ),
    ]
